//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('books')
export class booksEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  title: string;

  @Column('integer', { nullable: true })
  author: number;

  @Column('date', { nullable: true })
  publicationDate: Date;

  @Column('text', { nullable: true })
  isbn: string;

  @Column('text', { nullable: true })
  description: string;

  @Column('integer', { nullable: true })
  numberOfPages: number;
}
