//Source code generated by AppGPT (www.appgpt.tech)

//Class to create tables and seed new database
import { DataSource } from 'typeorm';
import { DBConfiguration } from './Configuration';
import { SettingsEntity } from './db/Settings.entity';
//autogenerate imports based on resources
import { booksEntity } from './db/books.entity';

export class Database {
  static dbConfiguration: DBConfiguration;
  public static ds: DataSource;

  static async Initialize(dbConfiguration: DBConfiguration) {
    Database.dbConfiguration = dbConfiguration;
    let dbConfig: any = dbConfiguration as any;
    //Autogenerate entities array from resource names

    dbConfig.entities = [SettingsEntity, booksEntity];
    Database.ds = new DataSource(dbConfig);
    await Database.ds.initialize();

    //TODO: Drop all tables

    await Database.Seed();
  }
  static async Seed() {
    let data: any = {
      books: [
        {
          title: 'The Great Gatsby',
          author: '1',
          publicationDate: '2022-01-15T10:30:00Z',
          isbn: '978-3-16-148410-0',
          description:
            'A classic novel depicting the decadence and disillusionment of the American Dream in the Jazz Age.',
          numberOfPages: 218,
        },
        {
          title: 'To Kill a Mockingbird',
          author: '2',
          publicationDate: '2021-09-05T14:45:00Z',
          isbn: '978-1-23-456789-0',
          description:
            'A powerful story of racial injustice and the loss of innocence in the Deep South.',
          numberOfPages: 324,
        },
        {
          title: '1984',
          author: '3',
          publicationDate: '2022-03-10T09:15:00Z',
          isbn: '978-9-87-654321-0',
          description:
            'A dystopian novel depicting a totalitarian regime and the struggle for individual freedom.',
          numberOfPages: 328,
        },
        {
          title: 'Pride and Prejudice',
          author: '4',
          publicationDate: '2021-11-20T16:00:00Z',
          isbn: '978-5-43-210987-6',
          description:
            'A classic romance novel exploring themes of love, class, and societal expectations.',
          numberOfPages: 432,
        },
        {
          title: 'The Catcher in the Rye',
          author: '5',
          publicationDate: '2022-02-28T11:20:00Z',
          isbn: '978-7-65-432109-8',
          description:
            'A coming-of-age story following the journey of a disillusioned teenager in New York City.',
          numberOfPages: 224,
        },
      ],
    };
    //Autogenerate multiple such calls ie for each resource and its data object
    let isSeeded = await this.IsSeeded();
    //if (!isSeeded) {
    //forcing app recreation
    if (true) {
      console.log('   Seeding database...');
      await this.SeedResource('booksEntity', data.books);
      await this.SeedResource('SettingsEntity', {
        settingname: 'isSeeded',
        settingvalue: 'true',
      });
    } else {
      console.log('   Database seeded already!');
    }
  }
  static async IsSeeded() {
    const repo = Database.ds.getRepository('SettingsEntity');
    let rec: any = await repo.findOne({
      select: {
        settingname: true,
        settingvalue: true,
      },
      where: {
        settingname: 'isSeeded',
      },
    });
    if (rec && rec.settingvalue) return true;
    return false;
  }
  static async SeedResource(resourceName: any, resourceData: any) {
    const repo = Database.ds.getRepository(resourceName);
    //await repo.clear();
    console.log('   Seeding table ' + resourceName);
    await repo.upsert(resourceData, ['id']);
  }
}
