//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    books: [
      {
        title: 'The Great Gatsby',
        author: '1',
        publicationDate: '2022-01-15T10:30:00Z',
        isbn: '978-3-16-148410-0',
        description:
          'A classic novel depicting the decadence and disillusionment of the American Dream in the Jazz Age.',
        numberOfPages: 218,
      },
      {
        title: 'To Kill a Mockingbird',
        author: '2',
        publicationDate: '2021-09-05T14:45:00Z',
        isbn: '978-1-23-456789-0',
        description:
          'A powerful story of racial injustice and the loss of innocence in the Deep South.',
        numberOfPages: 324,
      },
      {
        title: '1984',
        author: '3',
        publicationDate: '2022-03-10T09:15:00Z',
        isbn: '978-9-87-654321-0',
        description:
          'A dystopian novel depicting a totalitarian regime and the struggle for individual freedom.',
        numberOfPages: 328,
      },
      {
        title: 'Pride and Prejudice',
        author: '4',
        publicationDate: '2021-11-20T16:00:00Z',
        isbn: '978-5-43-210987-6',
        description:
          'A classic romance novel exploring themes of love, class, and societal expectations.',
        numberOfPages: 432,
      },
      {
        title: 'The Catcher in the Rye',
        author: '5',
        publicationDate: '2022-02-28T11:20:00Z',
        isbn: '978-7-65-432109-8',
        description:
          'A coming-of-age story following the journey of a disillusioned teenager in New York City.',
        numberOfPages: 224,
      },
    ],
  },
};
export default data;
