//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';
import grOriginal from 'ra-language-greek';

const enResources = {
  resources: {
    books: {
      name: 'Books',
      fields: {
        title: 'Title',
        author: 'Author',
        publicationDate: 'Publication Date',
        isbn: 'ISBN',
        description: 'Description',
        numberOfPages: 'Number of Pages',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    books: {
      name: 'Livres',
      fields: {
        title: 'Titre',
        author: 'Auteur',
        publicationDate: 'Date de publication',
        isbn: 'ISBN',
        description: 'Description',
        numberOfPages: 'Nombre de pages',
        id: 'id',
      },
    },
  },
};
const grResources = {
  resources: {
    books: {
      name: 'Βιβλία',
      fields: {
        title: 'Τίτλος',
        author: 'Συγγραφέας',
        publicationDate: 'Ημερομηνία δημοσίευσης',
        isbn: 'ISBN',
        description: 'Περιγραφή',
        numberOfPages: 'Αριθμός σελίδων',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);
const gr = mergeTranslations(grOriginal, grResources);

const translations = { en, fr, gr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
    { locale: 'gr', name: 'Ελληνικά' },
  ],
);
